server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pruebadb
    username: root
    password: 1234 
    driver-class-name: com.mysql.cj.jdbc.Driver

security:
  secretkey: mi_clave_secreta_segura_de_al_menos_32_bytes
  token-expiration: 86400000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
